# Generated by Django 4.2.3 on 2025-06-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productcomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='شناسه پیام تلگرام')),
                ('chat_id', models.CharField(max_length=100, verbose_name='شناسه چت')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_message', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پیام تلگرام',
                'verbose_name_plural': 'پیام\u200cهای تلگرام',
            },
        ),
    ]
