# Generated by Django 4.2.3 on 2025-06-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_telegrammessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramMessage',
        ),
    ]
