# Generated by Django 4.2.3 on 2025-07-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_delete_telegrammessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=100, null=True, verbose_name='تعداد'),
        ),
    ]
