# Generated by Django 4.2.3 on 2025-04-04 07:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_order_count_user_total_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[80, 80], upload_to='user_profile'),
        ),
    ]
